package com.alibaba.webplus.demo.controller;

/**
 * @author 白寂
 */
public enum EnvListEnum {
    // 环境
    WP_ENV_ID,
    WP_ENV_CREATE_TIME,
    WP_ENV_CREATE_USER,
    WP_ENV_NAME,

    // 变更
    WP_CHANGE_CREATE_TIME,
    WP_CHANGE_TRIGGER_USER,
    WP_CHANGE_NAME,
    WP_CHANGE_REQUEST_ID,
    WP_CHANGE_TRIGGER_FROM,
    WP_CHANGE_ID,

    // 部署包
    WP_PKG_VERSION_CREATE_TIME,
    WP_PKG_VERSION_LABEL,
    WP_PKG_VERSION_SOURCE,
    WP_PKG_VERSION_ID,
    WP_PKG_VERSION_ETAG,
    WP_PKG_VERSION_CREATE_USER,

    // 实例
    WP_INSTANCES_PRIVATE_IP,
    WP_INSTANCES_ID,

    // 应用
    WP_APP_ID,
    WP_APP_NAME,
    WP_APP_CATEGORY,
    WP_APP_CREATE_USER,
    WP_APP_CREATE_TIME,
    WP_APP_REGION_ID,

    // RDS
    WP_RDS_ENGINE,
    WP_RDS_CONNECTION_ADDRESS,
    WP_RDS_PORT,
    WP_RDS_ACCOUNT_NAME,
    WP_RDS_ACCOUNT_PASSWORD,
    WP_RDS_DATABASE,
}
